@startuml

actor Player
rectangle "Forbidden Island Game System" {
  usecase "Move Pawn"
  usecase "Shore Up Tile"
  usecase "Give Card"
  usecase "Capture Treasure"
  usecase "Play Special Card"
  usecase "Escape via Helicopter"
}
Player --> "Move Pawn"
Player --> "Shore Up Tile"
Player --> "Give Card"
Player --> "Capture Treasure"
Player --> "Play Special Card"
Player --> "Escape via Helicopter"

@enduml
